Trying ASDF instead

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,7 +4,7 @@
 ### Configure environment
 
 set -o errexit  # always exit on error
-set -o pipefail # don't ignore exit codes when piping output
+set -o pipefail # dont ignore exit codes when piping output
 set -o nounset  # fail on unset variables
 unset GIT_DIR   # Avoid GIT_DIR leak from previous build steps
 
@@ -41,35 +41,8 @@ install_binaries() {
   #local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
   #local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
 
-  curl -fsSL https://fnm.vercel.app/install | bash -s -- --install-dir "$BIN_DIR" --skip-shell
-  export PATH=$BUILD_DIR/.heroku/bin:$PATH
-  export NODE_OPTIONS=--max_old_space_size=4096
+  git clone https://github.com/asdf-vm/asdf.git $BIN_DIR/.asdf --branch v0.9.0
 
-  eval "$(fnm env)"
-
-  #if [ -n "$node_engine" ]; then
-  #  echo "-----> Install nodejs version $node_engine from package.json"
-  #  fnm install "$node_engine"
-  #else
-    echo "-----> Install nodejs version $DEFAULT_NODE_VERSION"
-    fnm install --log-level all --fnm-dir $BIN_DIR $DEFAULT_NODE_VERSION
-  #fi
-
-  #if [ -n "$npm_engine" ]; then
-  #  echo "-----> Install npm $npm_engine"
-  #  npm install -g "$npm_engine"
-  #else
-    echo "-----> Use default npm version"
-    npm -v
-    which npm
-  #fi
-
-  echo "-----> Install pnpm"
-  curl -sL https://unpkg.com/@pnpm/self-installer | node
-  pnpm config set store-dir "$CACHE_DIR"/.pnpm-store
-
-  echo "-----> Install pnpm"
-  pnpm install
 }
 
 install_binaries
